[workspace]
authors = ["Mark Servilla <mark.servilla@gmail.com>"]
channels = ["conda-forge"]
name = "iam-lib"
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = "3.12.*"
requests = ">=2.32.3,<3"
daiquiri = ">=3.0.0,<4"
pixi-pycharm = ">=0.0.8,<0.0.9"
pytest = ">=8.3.5,<9"
ruff = ">=0.11.8,<0.12"
pyjwt = ">=2.10.1,<3"
pip = ">=25.1.1,<26"
cryptography = ">=46.0.5,<47"
pytest-mock = ">=3.14.0,<4"
